[build]
  command = "yarn rw build && yarn rw prisma migrate deploy && yarn rw data-migrate up"
  publish = "web/dist"
  functions = "api/dist/functions"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/200.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", ".prisma/client"]
  directory = "api/dist/functions"
  # Setze die Region deiner Funktionen, um eine stabile Verbindung zur Datenbank zu gewährleisten.
  region = "eu-central-1"

# To use Netlify Dev, install Netlify's CLI (`netlify-cli`) from NPM and use `netlify link`
# to connect your local project to a site on Netlify. Then run `netlify dev`.
#
# Quick links to the docs:
# - Netlfy Dev https://www.netlify.com/products/dev
# - Netlify's CLI https://docs.netlify.com/cli/get-started/#installation
# - `netlify link` https://docs.netlify.com/cli/get-started/#link-and-unlink-sites
[dev]
  framework = "redwoodjs"
  # Make sure `targetPort` matches `web.port` in the `redwood.toml`:
  targetPort = 8910
  # Point your browser to this port to access your app:
  port = 8888
