[build]
  command = "yarn rw deploy netlify"
  publish = "web/dist"
  functions = "api/dist/functions"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/200.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", ".prisma/client"]
  directory = "api/dist/functions"
  region = "eu-central-1"

[functions."*"]
  node_bundler = "esbuild"
